apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: staging
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_ME_IN_PIPELINE"
  DATABASE_URL: "postgres://payday:REPLACE_ME_IN_PIPELINE@postgres:5432/payday?sslmode=disable"
