apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-api-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/payday_platform
    targetRevision: main
    path: k8s/apps/auth-api
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
